### ISSUE TITLE
Missing dependency on eex in mix.exs

### ISSUE THREAD

**Issue by ericbmerritt** [CargoSense/vex#26]
Vex has a dependency on eex, that is not specified in the mix. When using tools like relx, to build releases that include vex that dependency is not bundled up casing things to fail. The fix is to add eex as a dependency of vex (and any other implicit dependencies that might exist).

**Comment by ShaneKilkelly** [comment]
I'm looking into this issue, and it doesn't appear to be possible to add a built-in module such as `EEx` as a mix dependency.

However, it's possible this issue would be solved by adding `:eex` to the applications list instead.

Do you have an example of a minimal relx setup that can replicate this issue? If so I can test my fix and get it merged in.

Thanks!

**Comment by benwilson512** [comment]
It's entirely possible that `vex` should have `:eex` on the applications list.

**Comment by benwilson512** [comment]
Fixed in master.
