### ISSUE TITLE
Validation Context

### ISSUE THREAD

**Issue by asummers** [CargoSense/vex#32]
Question, perhaps a feature request:

Suppose as part of my validation steps that I need to hit the database to get some objects out of them. I would like to be able to pass the already queried objects around in some sort of context object to the various validators in a validation pipeline, such that they are able to ask the context for them and not have to requery the database. What would be the best way to accomplish this? 

Borrowing an example from the readme, I'd imagine it'd look something like:
```
Vex.valid?(user, password: fn (context, password) ->
  if context.user.password = hash(password) do
    {:ok, context}
  else
    {:error, "#{password} mismatch"}
  end
end)
```

Then the pattern match for the `:ok` in the caller (https://github.com/CargoSense/vex/blob/master/lib/vex.ex#L49) could simply forward the previous context around for the `/1` validators.

**Comment by djspinmonkey** [comment]
I'm a bit new to Elixir, so still learning all the idioms and common practices, but my off-the-cuff reaction is that if you have a function that fetches and caches users (or other resources), you could just call that from the validator without any special plumbing. It's possible I don't quite have my head wrapped around some aspect of what you're asking for, though.

Eg, would something like this work? (I made it validate the author on a post object, which seemed to make a little more sense in terms of something that would be pulled out of the database during validation.)

```elixir
defmodule User
  def find(id)
    # return the cached User if present
    # otherwise, fetch user data from DB, store it in the cache, and return
  end
end

Vex.valid?(post, author_id: fn author_id ->
  author = User.find(author_id)   # gets the cached User if we've already looked it up
  Vex.valid?(author)
end
```

You could explicitly pass in the cache, too, if you wanted to exactly duplicate the behavior in your example (if I understand it correctly).

Anyway, does that make sense, or am I missing something?

**Comment by asummers** [comment]
You could do that. We wound up not using this and just using Ecto schemas with custom validation steps, which lets you call cast_assoc and get the behavior I described.

**Comment by djspinmonkey** [comment]
Ah, ok. I'll go ahead and close this for now, then, since there's nobody actively asking for it. Let me know if it turns out it would be useful for you at some point in the future (or if anybody else is following along, feel free to leave a comment), and I can re-open it.

**Comment by InteNs** [comment]
I need to validate that the end_date is before the start_date in my model, afaik this isn't possible without this context.

```elixir
defmodule PlonquoApi.Steps.Activity.StopActivity do
  defstruct activity:       nil,
            realised_start: nil,
            realised_end:   DateTime.utc_now

  use Vex.Struct

  validates :activity,       presence: true
  validates :realised_start, presence: true
  validates :realised_end,   [
    presence: true,
    by: fn (context, realised_end) -> realised_end > context.activity.realised_start end
  ]
end

```

**Comment by jfornoff** [comment]
For the record, this kind of behavior is possible, the whole struct is passed to the second parameter of the `by`-function.
However, it might be that you need to return `:ok` or an `{:error, <message>}` tuple.
