### ISSUE TITLE
Validator contributions

### ISSUE THREAD

**Issue by jfornoff** [CargoSense/vex#46]
Hi there,

would you be interested in contributions of additional validators, more specifically:
- Number validation, currently containing
  - `is_number`
  - `greater_than`
  - `less_than`
  - `greater_or_equal_than`
  - `integer`

- UUID validation
- (whole-struct validation, `validate :field, invalid: [if: Some.function/1]`, this is more of a workaround though.)

Just wanted to hear if you're interested before preparing an eventual PR.
Cheers,
Jan

**Comment by indyone** [comment]
Hi @jfornoff i have created many of these validators you mention... but as a separate project that provides Vex Validator modules and can be used as sources.

Would like to have a look of my work at https://github.com/StoiximanServices/vex_validators?
If you like them, I can create a PR!

**Comment by jfornoff** [comment]
Hi @indyone, thanks for getting in touch and offering your contribution!

I think this would be great, we have a lot of overlapping functionality to your validators in our project which we could merge together.

Maybe you could drop a PR and we'll look at how our solutions fit together in the review?
cc @Zeeker

**Comment by KamilLelonek** [comment]
@indyone any plans for doing that?

**Comment by indyone** [comment]
Yes... I can do that for. I will do within this week. :)

**Comment by indyone** [comment]
@KamilLelonek check #55 :)

**Comment by Zeeker** [comment]
I think we can close this, right?
